name: Bug Report
description: Report a bug
title: "[Bug]: "
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Please read [this](https://engineering.hmn.md/projects/support/) before proceeding forward.
        
        Please note that we don't offer detailed end-user support.

        This template is just for bug reports, not for questions.
        
        If the opened issue doesn't have all of the needed information, or it's off-topic, we will close it. 
        
        Please provide as much details as possible - some bugs are hard to investigate and reproduce.
        
        Thank you for helping us fix our product.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A short description of what the bug is
      placeholder: Describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce and Code Sample
      description: Precise steps to reproduce the behaviour. You can also add minimal code sample that reproduces the issue.
      placeholder: |
        Step 1
        Step 2
        Step 3...
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: Description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Info
      description: Add any other info about the problem here (screenshots, videos, related issues, etc.)
      placeholder: Additional information that might help. Error messages, logs, screenshots, your device, OS version, browser version, etc.
    validations:
      required: false
