name: Feature Request
description: Submit a feature request
title: "[Feature]: "
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Please read [this](https://engineering.hmn.md/projects/support/) before proceeding forward.
        
        Please note that we don't offer detailed end-user support.

        This template is just for feature requests, not for questions.
        
        If the opened issue doesn't have all of the needed information, or it's off-topic, we will close it.
        
        Please provide as much details as possible about the feature you need.
        
        Thank you for helping us build a better product.

  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour and Context
      description: Describe the scenario that led to this request.
      placeholder: How is it working now?
    validations:
      required: true
      
  - type: textarea
    id: improved_behaviour
    attributes:
      label: Improved Behaviour
      description: Description of how things should work.
      placeholder: How it should be working?
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Info
      description: Any additional info, including ideas or examples of how this could be implemented.
      placeholder: Share your thoughts, examples, or references.
    validations:
      required: false
