source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "webrick", "~> 1.8"
gem "just-the-hm-docs", github: "humanmade/just-the-hm-docs"
gem "csv", "~> 3.3"

group :jekyll_plugins do
  gem "jekyll-include-cache"
end
